add quality check

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,5 +1,6 @@
 stages:
     - testing
+    - quality-check
     - build
 
 variables:
@@ -32,6 +33,29 @@ test fe:
     artifacts:
       paths:
         - "coverage.out"
+
+be code quality: 
+    stage: quality-check
+    tags:
+      - gcp-go
+    needs:
+      - job: testing
+        artifacts: true
+    variables: 
+      TEST_THRESHOLD: $TEST_THRESHOLD
+    script: 
+        - echo "quality check"
+        - echo "Threshold  -> $TEST_THRESHOLD %"
+        - totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+        - echo "Current test coverage -> $totalCoverage %"
+        - > 
+          if (( $(echo "$totalCoverage $TEST_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+              echo "OK"
+          else
+              echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+              echo "Failed"
+              exit 1
+          fi
 
 build be:
     stage: build
